"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const cors_1 = __importDefault(require("cors"));
const dotenv_1 = __importDefault(require("dotenv"));
const pendingActions_1 = __importDefault(require("./routes/pendingActions"));
const profiles_1 = __importDefault(require("./routes/profiles"));
const insightsChart_1 = __importDefault(require("./routes/insightsChart"));
dotenv_1.default.config();
const app = (0, express_1.default)();
app.use((0, cors_1.default)());
app.use(express_1.default.json());
app.use("/api/pending-actions", pendingActions_1.default);
app.use("/api/profiles", profiles_1.default);
app.use("/api/insights", insightsChart_1.default);
const PORT = process.env.PORT || 5050;
app.listen(PORT, () => console.log(`API running on port ${PORT}`));
